### ISSUE TITLE
What is the file access order?

### ISSUE THREAD

**Issue by MomentQYC** [matrix-org/synapse-s3-storage-provider#113]
I noticed that Synapse will store the files locally at the same time, so does Synapse prioritize reading from local, prioritize reading from the S3 service when it needs to read the files, or both? If the latter two, is there any way to change to the first read order?

**Comment by erikjohnston** [comment]
Synapse will try to read from the local disk first, and then will try reading from each storage provider (in the order defined in the Synapse config).

**Comment by MomentQYC** [comment]
> Synapse will try to read from the local disk first, and then will try reading from each storage provider (in the order defined in the Synapse config).

Does Synapse still request files from S3 after reading them locally?

**Comment by erikjohnston** [comment]
Synapse will return the file once it's found it, so no it won't try other storage providers (e.g. S3) if the file is found locally
