### ISSUE TITLE
PyPI/PyPA package?

### ISSUE THREAD

**Issue by lullis** [matrix-org/synapse-s3-storage-provider#22]
It would be great to have this application available directly on PyPI servers. Any reason it hasn't been done yet?

**Comment by HarHarLinks** [comment]
you can install from VCS easily using pip:
`pip install git+https://github.com/matrix-org/synapse-s3-storage-provider`

**Comment by lullis** [comment]
Yes, I know that is possible. However, it is not an answer to the question.

The reason that a "plain pip" package is desirable. I would like to automate the installation of a series of matirix servers. Depending on git forces me to install another dependency on the machine, and not having an actual release prevents me from pinning the version of this package.

synapse itself already has a pip package. Is there any reason that this module can not also have one as well? Perhaps I could help.

**Comment by clokep** [comment]
I suspect there isn't any particular reason -- just that doing official releases requires a bunch of additional procedure. If this is already installable via pip that's good, we might need to just setup some changelogs and such.

**Comment by richvdh** [comment]
we expect to be doing a bit of work on this project in the near future; we'll try to incorporate this as part of it.

**Comment by ShadowJonathan** [comment]
I recently came across this problem when making a synapse container with this plugin inside of it (#14), I tried to use this Dockerfile configuration first:

```Dockerfile
FROM matrixdotorg/synapse:latest

RUN git clone https://github.com/matrix-org/synapse-s3-storage-provider.git && \
        cd /synapse-s3-storage-provider && \
        pip install .
```

I compounded that down to 

```Dockerfile
...
RUN pip install git+https://github.com/matrix-org/synapse-s3-storage-provider
```

But in both cases it failed, because git wasn't installed.

`apk` wasn't present, and `apt` wasnt up-to-date (i couldnt do `apt install git -y` right off the bat)

This is what i settled with:

```Dockerfile
...
RUN apt update && apt install git -y && \
      pip install git+https://github.com/matrix-org/synapse-s3-storage-provider
```

Publishing just a package would clutter less, like this.

**Comment by inaniyants** [comment]
Hi! This package was published to pip registry on May 18, 2021. So this issue could be closed now.
Here are details:
https://github.com/matrix-org/synapse-s3-storage-provider/issues/14#issuecomment-847146994
