### ISSUE TITLE
Allow configuration of timeout for s3 storage provider downloads/uploads

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse-s3-storage-provider#31]
A task from a previous PR that would be useful to fix 'sometime', but does not block that PR.

https://github.com/matrix-org/synapse-s3-storage-provider/pull/30#discussion_r370255268

**Comment by richvdh** [comment]
Are you sure this needs to be configurable? I don't think the setting does what you think it does: it's the amount of time the Matrix client gets to start re-reading data after we fill its buffer with data read from S3. In particular it's not a thing that seems like it would need adjusting for large files.

**Comment by michaelkaye** [comment]
Ah, this does not do what i thought it did. So is probably not worth configuring.
