### ISSUE TITLE
Installation Procedures?

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [matrix-org/synapse-s3-storage-provider#42]
I'm sorry for posting such a basic question but I really don't know what to do since I have done little with Python.
I'm currently using the prebuilt package of Synapse on my Ubuntu machine, and I am just wondering how I can satisfy the requirement that "the `s3_storage_provider.py` should be on the `PYTHONPATH`". Thank you!

**Comment by richvdh** [comment]
dup #14
