### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by subhashkumar-kiwi** [matrix-org/synapse-s3-storage-provider#6]
I have istalled boto3 and make configure in .aws folder at the root of the directory.But when I share any image still it store locally.

**Comment by djmaze** [comment]
Synapse seems to store the files in S3 [as well as locally](https://github.com/matrix-org/synapse/blob/74854a97191191b08101821753c2672efc2a65fd/synapse/rest/media/v1/media_storage.py#L53-L55). But in this case the local directory is used [as a cache only](https://github.com/matrix-org/synapse/blob/74854a97191191b08101821753c2672efc2a65fd/synapse/rest/media/v1/media_storage.py#L131-L133). 

I just deleted everything from my synapse's `media` directory. I can still download all files from Riot. Works for me!
