### ISSUE TITLE
Please push latest changes for synapse v.1.45.0 to PyPi

### ISSUE THREAD

**Issue by patrickstump** [matrix-org/synapse-s3-storage-provider#64]
**Describe the bug**

The [version 1.0 in PyPi](https://pypi.org/project/synapse-s3-storage-provider) does not contain the latest update required to be compatible with synapse v1.45.0.
This [commit](https://github.com/matrix-org/synapse-s3-storage-provider/commit/fd1e12385ddc7cca7d9bf3cf7cbcff1c35c42f21) has the necessary changes.

When starting the synapse v1.45.0 server with a working config and the [version 1.0 from PyPi](https://pypi.org/project/synapse-s3-storage-provider), installed via pip, the following error crashes the media worker.

```
AttributeError: 'HomeServerConfig' object has no attribute 'media_store_path'
```

**To Reproduce**
1. Install this storage provider from pip
```pip3 install synapse-s3-storage-provider```
2. Run synapse with a homeserver config using this module.

**Expected behavior**
Start up with existing correct config with no error.

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by patrickstump** [comment]
Thank you for the update and the install procedure.

**Comment by AlexanderBabel** [comment]
Hey, I currently maintain the PyPi package. I just updated it to the latest version.

BTW, I would be glad if we could add support for automatic pushing through GitHub workflows.
Also, I would be happy to change to ownership of the package to someone from matrix-org.

**Comment by DMRobertson** [comment]
Hi @AlexanderBabel, thanks for reaching out to us. We'd like to transfer ownership to a generic matrix.org account on PyPI, as you suggest. I'll contact you directly to discuss!

**Comment by DMRobertson** [comment]
Thanks @AlexanderBabel for your help. https://pypi.org/project/synapse-s3-storage-provider/ is now owned by https://pypi.org/user/matrixdotorg/. I'll publish an update now.

**Comment by DMRobertson** [comment]
> I'll publish an update now.

Ahh, I missed that you had updated the package a few days ago. I'm working to get an automatic release process setup for this and our other modules.
