### ISSUE TITLE
CI is utterly broken

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse-s3-storage-provider#82]
Noticed in https://github.com/matrix-org/synapse-s3-storage-provider/pull/80

https://github.com/matrix-org/synapse-s3-storage-provider/commit/ffd3fa477321608e57d27644197e721965e0e858 was good

https://github.com/matrix-org/synapse-s3-storage-provider/commit/5a70b9ac8f21b11cafa78f78f5c7571ad8ad8b28 was bad: [integration test failed](https://github.com/matrix-org/synapse-s3-storage-provider/actions/runs/2977969293/jobs/4772286737)

Then in https://github.com/matrix-org/synapse-s3-storage-provider/commit/e762c859ac7910e043f09f45a657ff607c66a599 the unit tests suddenly started failing: https://github.com/matrix-org/synapse-s3-storage-provider/actions/runs/3233934664/jobs/5296573191 . Was unable to reproduce this on my machine

**Comment by H-Shay** [comment]
I see this was added and removed from the discussion board but I have no memory of what was decided/determined: does anyone remember the outcome of this discussion?

**Comment by DMRobertson** [comment]
Discussion was: yeah, we should fix this. It's on the planning board if anyone wants to pick it up.
