### ISSUE TITLE
can not connect to homeserver db with unix socket peer authentication

### ISSUE THREAD

**Issue by yu-re-ka** [matrix-org/synapse-s3-storage-provider#98]
My configuration does not contain a database password, because none is required.

```
    password=database_args["password"],
KeyError: 'password'
```

**Comment by reivilibre** [comment]
are you able to try and see if replacing this line https://github.com/matrix-org/synapse-s3-storage-provider/blob/1beb6af95e1f5caedb8e6e7e1cc176cdb2106d37/scripts/s3_media_upload#L418

with

```python
password=database_args.get("password"),
```

makes that work?

If so, this should be an easy fix.

**Comment by H-Shay** [comment]
Any updates on this?
